name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: pages
      cancel-in-progress: false
    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: Deploy GitHub Pages
        uses: peaceiris/actions-gh-pages@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./   # Root-Ordner mit HTML + Medien
          publish_branch: gh-pages   # Branch, auf den GitHub Pages deployed
